/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/cppFiles/class.cc to edit this template
 */

/* 
 * File:   CppForG.cpp
 * Author: rlcancian
 * 
 * Created on 11 de janeiro de 2022, 22:37
 */


#include "CppForG.h"
#include "../../kernel/simulator/Model.h"

#include <fstream>
#include <dlfcn.h>
#include <string>

#ifdef PLUGINCONNECT_DYNAMIC

extern "C" StaticGetPluginInformation GetPluginInformation() {
	return &CppForG::GetPluginInformation;
}
#endif

ModelDataDefinition* CppForG::NewInstance(Model* model, std::string name) {
	return new CppForG(model, name);
}

CppForG::CppForG(Model* model, std::string name) : ModelComponent(model, Util::TypeOf<CppForG>(), name) {
	_createInternalAndAttachedData();
}

std::string CppForG::show() {
	return ModelComponent::show() + "";
}

ModelComponent* CppForG::LoadInstance(Model* model, PersistenceRecord *fields) {
	CppForG* newComponent = new CppForG(model);
	try {
		newComponent->_loadInstance(fields);
	} catch (const std::exception& e) {

	}
	return newComponent;
}

void CppForG::setCppCompiler(CppCompiler* _cppCompiler) {
	this->_cppCompiler = _cppCompiler;
}

CppCompiler* CppForG::getCppCompiler() const {
	return _cppCompiler;
}

void CppForG::setInitBetweenReplicationCode(std::string _initBetweenReplicationCode) {
	this->_initBetweenReplicationCode = _initBetweenReplicationCode;
}

std::string CppForG::getInitBetweenReplicationCode() const {
	return _initBetweenReplicationCode;
}

void CppForG::setOnDispatchEventCode(std::string _onDispatchEventCode) {
	this->_onDispatchEventCode = _onDispatchEventCode;
}

std::string CppForG::getOnDispatchEventCode() const {
	return _onDispatchEventCode;
}

void CppForG::setIncludesCode(std::string _includesCode) {
	this->_includesCode = _includesCode;
}

std::string CppForG::getIncludesCode() const {
	return _includesCode;
}

void CppForG::_onDispatchEvent(Entity* entity, unsigned int inputPortNumber) {
	_parentModel->getTracer()->trace("Invoking cpp user code for dispatchEvent");
	try {
		dispatchEvent(entity, _parentModel);
	} catch (...) {

	}
	this->_parentModel->sendEntityToComponent(entity, this->getConnections()->getFrontConnection());
}

bool CppForG::_loadInstance(PersistenceRecord *fields) {
	bool res = ModelComponent::_loadInstance(fields);
	if (res) {
		// @TODO: not implemented yet
	}
	return res;
}

//void CppForG::_initBetweenReplications() {}

void CppForG::_saveInstance(PersistenceRecord *fields, bool saveDefaultValues) {
	ModelComponent::_saveInstance(fields, saveDefaultValues);
	// @TODO: not implemented yet
}

bool CppForG::_check(std::string* errorMessage) {
	bool resultAll = true;
	CppCompiler::CompilationResult result;
	std::string name = this->getName();
	std::string sourceCode = "\
//\n\
// File automatically generated by GenESyS CppForG plugin\n\
// Date: \n\
//\n\
#include <iostream>\n\
#include <string>\n\
#include \"../../../../kernel/simulator/Entity.h\"  // TODO: Adjust depending on running path\n\
#include \"../../../../kernel/simulator/Model.h\"  // TODO: Adjust depending on running path\n\
// user includes\n\
" + this->_includesCode + "\n\
\n\
void _onDispatchEvent_" + name + "(Entity* entity, Model* model) {\n\
	// user code\n\
" + this->_onDispatchEventCode + "\n\
}\n\
\n\
void _initBetweenReplications_" + name + "(Model* model) {\n\
	// user code\n\
" + this->_initBetweenReplicationCode + "\n\
}\n\
\n\
extern \"C\" void onDispatchEvent_" + name + "(Entity* entity, Model* model) {\n\
	try {\n\
		_onDispatchEvent_" + name + "(entity, model);\n\
	} catch (const std::exception& e) {\n\
		model->getTracer()->traceError(e, \"Error while executing onDispatchEvent cpp user code in " + name + ".\");\n\
	}\n\
}\n\
\n\
extern \"C\" void initBetweenReplications_" + name + "(Model* model) {\n\
	try {\n\
		_initBetweenReplications_" + name + "(model);\n\
	} catch (const std::exception& e) {\n\
		model->getTracer()->traceError(e, \"Error while executing initBetweenReplications cpp user code in " + name + ".\");\n\
	}\n\
}\n";
	// save the code for the compiler
	_sourceFilename = "./" + getName() + ".cpp";
	_outputFilename = "./" + getName() + ".so";
	try {
		_parentModel->getTracer()->trace("Saving source file \"" + _sourceFilename + "\"");
		std::ofstream outfile(_sourceFilename);
		outfile << sourceCode;
		outfile.close();
	} catch (...) {
		resultAll = false;
		*errorMessage += "Error saving source code to compile";
	}
	// if saved, compile
	if (resultAll) {
		_parentModel->getTracer()->trace("Compiling source file \"" + _sourceFilename + "\"");
		_cppCompiler->setSourceFilename(_sourceFilename);
		_cppCompiler->setOutputFilename(_outputFilename);
		std::string objectFiles = "Simulator.o Model.o ModelComponent.o ModelDataDefinition.o Entity.o Util.o Attribute.o EntityType.o StatisticsCollector.o StatisticsDefaultImpl1.o"; // TODO COMPLETE...
		_cppCompiler->setObjectFiles(objectFiles);
		CppCompiler::CompilationResult result = _cppCompiler->compileToDynamicLibrary();
		if (!result.success) {
			resultAll = false;
			*errorMessage += result.compilationErrOutput;
		}
	}
	// if compiled, load dynamic library
	if (resultAll) {
		_cppCompiler->unloadLibrary();
		_parentModel->getTracer()->trace("Loading dynamic library \"" + _outputFilename + "\"");
		resultAll = _cppCompiler->loadLibrary(errorMessage);
		if (!resultAll) {
			*errorMessage += ". Error loading dynamic library.";
		}
	}
	// if dynamic library loaded, then vinculate pointers to loaded functions
	if (resultAll) {
		_parentModel->getTracer()->trace("Vinculating dynamic library functions");
		try {
			void* handle = _cppCompiler->getDynamicLibraryHandle();
			std::string strdispatchFunctionName = "onDispatchEvent_" + name;
			const char *dispatchFunctionName = strdispatchFunctionName.c_str();
			dispatchEvent = (void(*)(Entity*, Model*))dlsym(handle, dispatchFunctionName);
			std::string strinitFunctionName = "initBetweenReplications_" + name;
			const char *initFunctionName = strinitFunctionName.c_str();
			initBetweenReplications = (void(*)(Model*))dlsym(handle, initFunctionName);
		} catch (...) {
			resultAll = false;
			*errorMessage += "Error vinculating library functions";
		}
	} else {
		dispatchEvent = nullptr;
		initBetweenReplications = nullptr;
	}
	return resultAll;
}

void CppForG::_initBetweenReplications() {
	//@ TODO
	try {
		initBetweenReplications(_parentModel);
	} catch (...) {

	}
}

void CppForG::_createInternalAndAttachedData() {
	if (_parentModel->isAutomaticallyCreatesModelDataDefinitions()) {
		if (_cppCompiler == nullptr) {
			_cppCompiler = new CppCompiler(_parentModel, getName() + ".CppCompiler");
			_cppCompiler->setSourceFilename(getName() + ".cpp");
			_cppCompiler->setOutputFilename(getName() + ".so");
			_internalDataInsert("CppCompiler", _cppCompiler);
		}
	}
}

PluginInformation* CppForG::GetPluginInformation() {
	PluginInformation* info = new PluginInformation(Util::TypeOf<CppForG>(), &CppForG::LoadInstance, &CppForG::NewInstance);
	info->setCategory("Logic");
	info->insertDynamicLibFileDependence("cppcompiler.so");
	info->setDescriptionHelp("//@TODO");
	return info;
}
