QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
QT += printsupport

CONFIG += c++14

# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
	../../../source/applications/BaseConsoleGenesysApplication.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/AnimateExpression.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/CodeEditor.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalComponentPort.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalConnection.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalModelComponent.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalModelDataDefinition.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/ModelGraphicsScene.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/ModelGraphicsView.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/PropertyEditor.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/SimpleQtGUI.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/dialogBreakpoint.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/main.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/mainwindow.cpp \
	../../../source/applications/gui/qt/GenesysQtGUI/qcustomplot.cpp \
	../../../source/examples/book/Book_Cap02_Example01.cpp \
	../../../source/examples/smarts/Smart_AssignWriteSeizes.cpp \
	../../../source/examples/smarts/Smart_BatchSeparate.cpp \
	../../../source/examples/smarts/Smart_CellularAutomata1.cpp \
	../../../source/examples/smarts/Smart_CppForG.cpp \
	../../../source/examples/smarts/Smart_Delay.cpp \
	../../../source/examples/smarts/Smart_Dummy.cpp \
	../../../source/examples/smarts/Smart_HoldSignal.cpp \
	../../../source/examples/smarts/Smart_ModelInfoModelSimulation.cpp \
	../../../source/examples/smarts/Smart_ODE.cpp \
	../../../source/examples/smarts/Smart_OnEvent.cpp \
	../../../source/examples/smarts/Smart_Parser.cpp \
	../../../source/examples/smarts/Smart_ParserModelFunctions.cpp \
	../../../source/examples/smarts/Smart_Plugin.cpp \
	../../../source/examples/smarts/Smart_Process.cpp \
	../../../source/examples/smarts/Smart_ProcessSet.cpp \
	../../../source/examples/smarts/Smart_RouteStation.cpp \
	../../../source/examples/smarts/Smart_SeizeDelayRelease.cpp \
	../../../source/examples/smarts/Smart_SeizeDelayReleaseMany.cpp \
	../../../source/examples/smarts/Smart_Sequence.cpp \
	../../../source/examples/teaching/AnElectronicAssemblyAndTestSystem.cpp \
	../../../source/examples/teaching/FullSimulationOfComplexModel.cpp \
	../../../source/examples/teaching/OperatingSystem02.cpp \
	../../../source/examples/teaching/OperatingSystem03.cpp \
	../../../source/kernel/simulator/Attribute.cpp \
	../../../source/kernel/simulator/ComponentManager.cpp \
	../../../source/kernel/simulator/ConnectionManager.cpp \
	../../../source/kernel/simulator/Counter.cpp \
	../../../source/kernel/simulator/Entity.cpp \
	../../../source/kernel/simulator/EntityType.cpp \
	../../../source/kernel/simulator/Event.cpp \
	../../../source/kernel/simulator/ExperimentManager.cpp \
	../../../source/kernel/simulator/ExperimentManagerDefaultImpl1.cpp \
	../../../source/kernel/simulator/LicenceManager.cpp \
	../../../source/kernel/simulator/Model.cpp \
	../../../source/kernel/simulator/ModelCheckerDefaultImpl1.cpp \
	../../../source/kernel/simulator/ModelComponent.cpp \
	../../../source/kernel/simulator/ModelDataDefinition.cpp \
	../../../source/kernel/simulator/ModelDataManager.cpp \
	../../../source/kernel/simulator/ModelInfo.cpp \
	../../../source/kernel/simulator/ModelManager.cpp \
	../../../source/kernel/simulator/ModelPersistenceDefaultImpl1.cpp \
	../../../source/kernel/simulator/ModelSimulation.cpp \
	../../../source/kernel/simulator/OnEventManager.cpp \
	../../../source/kernel/simulator/ParserChangesInformation.cpp \
	../../../source/kernel/simulator/ParserDefaultImpl1.cpp \
	../../../source/kernel/simulator/ParserDefaultImpl2.cpp \
	../../../source/kernel/simulator/ParserManager.cpp \
	../../../source/kernel/simulator/Plugin.cpp \
	../../../source/kernel/simulator/PluginConnectorDummyImpl1.cpp \
	../../../source/kernel/simulator/PluginInformation.cpp \
	../../../source/kernel/simulator/PluginManager.cpp \
	../../../source/kernel/simulator/Property.cpp \
	../../../source/kernel/simulator/PropertyManager.cpp \
	../../../source/kernel/simulator/SimulationExperiment.cpp \
	../../../source/kernel/simulator/SimulationReporterDefaultImpl1.cpp \
	../../../source/kernel/simulator/SimulationScenario.cpp \
	../../../source/kernel/simulator/Simulator.cpp \
	../../../source/kernel/simulator/SinkModelComponent.cpp \
	../../../source/kernel/simulator/SourceModelComponent.cpp \
	../../../source/kernel/simulator/StatisticsCollector.cpp \
	../../../source/kernel/simulator/TraceManager.cpp \
	../../../source/kernel/simulator/parserBisonFlex/Genesys++-driver.cpp \
	../../../source/kernel/simulator/parserBisonFlex/Genesys++-scanner.cpp \
	../../../source/kernel/simulator/parserBisonFlex/GenesysParser.cpp \
	../../../source/kernel/simulator/parserBisonFlex/obj_t.cpp \
	../../../source/kernel/statistics/CollectorDatafileDefaultImpl1.cpp \
	../../../source/kernel/statistics/CollectorDefaultImpl1.cpp \
	../../../source/kernel/statistics/SamplerBoostImpl.cpp \
	../../../source/kernel/statistics/SamplerDefaultImpl1.cpp \
	../../../source/kernel/statistics/SorttFile.cpp \
	../../../source/kernel/statistics/StatisticsDataFileDefaultImpl.cpp \
	../../../source/kernel/statistics/StatisticsDefaultImpl1.cpp \
	../../../source/kernel/util/Util.cpp \
	../../../source/plugins/components/Access.cpp \
	../../../source/plugins/components/Assign.cpp \
	../../../source/plugins/components/Batch.cpp \
	../../../source/plugins/components/CellularAutomata.cpp \
	../../../source/plugins/components/CppForG.cpp \
	../../../source/plugins/components/Create.cpp \
	../../../source/plugins/components/Decide.cpp \
	../../../source/plugins/components/Delay.cpp \
	../../../source/plugins/components/Dispose.cpp \
	../../../source/plugins/components/DropOff.cpp \
	../../../source/plugins/components/DummyComponent.cpp \
	../../../source/plugins/components/Enter.cpp \
	../../../source/plugins/components/Exit.cpp \
	../../../source/plugins/components/Hold.cpp \
	../../../source/plugins/components/LSODE.cpp \
	../../../source/plugins/components/Leave.cpp \
	../../../source/plugins/components/MarkovChain.cpp \
	../../../source/plugins/components/Match.cpp \
	../../../source/plugins/components/OLD_ODEelement.cpp \
	../../../source/plugins/components/PickStation.cpp \
	../../../source/plugins/components/PickUp.cpp \
	../../../source/plugins/components/Process.cpp \
	../../../source/plugins/components/QueueableItem.cpp \
	../../../source/plugins/components/Record.cpp \
	../../../source/plugins/components/Release.cpp \
	../../../source/plugins/components/Remove.cpp \
	../../../source/plugins/components/Route.cpp \
	../../../source/plugins/components/Search.cpp \
	../../../source/plugins/components/SeizableItem.cpp \
	../../../source/plugins/components/Seize.cpp \
	../../../source/plugins/components/Separate.cpp \
	../../../source/plugins/components/Signal.cpp \
	../../../source/plugins/components/Start.cpp \
	../../../source/plugins/components/Stop.cpp \
	../../../source/plugins/components/Store.cpp \
	../../../source/plugins/components/Submodel.cpp \
	../../../source/plugins/components/Unstore.cpp \
	../../../source/plugins/components/Write.cpp \
	../../../source/plugins/data/AssignmentItem.cpp \
	../../../source/plugins/data/CppCode.cpp \
	../../../source/plugins/data/DummyElement.cpp \
	../../../source/plugins/data/EntityGroup.cpp \
	../../../source/plugins/data/Failure.cpp \
	../../../source/plugins/data/File.cpp \
	../../../source/plugins/data/Formula.cpp \
	../../../source/plugins/data/Label.cpp \
	../../../source/plugins/data/Queue.cpp \
	../../../source/plugins/data/Resource.cpp \
	../../../source/plugins/data/Schedule.cpp \
	../../../source/plugins/data/Sequence.cpp \
	../../../source/plugins/data/Set.cpp \
	../../../source/plugins/data/Station.cpp \
	../../../source/plugins/data/Storage.cpp \
	../../../source/plugins/data/Variable.cpp \
	../../../source/tools/HypothesisTesterDefaultImpl1.cpp \
	../../../source/tools/ProbabilityDistribution.cpp \
	../../../source/tools/SolverDefaultImpl1.cpp

HEADERS += \
	../../../source/applications/BaseConsoleGenesysApplication.h \
	../../../source/applications/GenesysApplication_if.h \
	../../../source/applications/gui/qt/GenesysQtGUI/AnimateExpression.h \
	../../../source/applications/gui/qt/GenesysQtGUI/CodeEditor.h \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalComponentPort.h \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalConnection.h \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalModelComponent.h \
	../../../source/applications/gui/qt/GenesysQtGUI/GraphicalModelDataDefinition.h \
	../../../source/applications/gui/qt/GenesysQtGUI/LineNumberArea.h \
	../../../source/applications/gui/qt/GenesysQtGUI/ModelGraphicsScene.h \
	../../../source/applications/gui/qt/GenesysQtGUI/ModelGraphicsView.h \
	../../../source/applications/gui/qt/GenesysQtGUI/PropertyEditor.h \
	../../../source/applications/gui/qt/GenesysQtGUI/SimpleQtGUI.h \
	../../../source/applications/gui/qt/GenesysQtGUI/dialogBreakpoint.h \
	../../../source/applications/gui/qt/GenesysQtGUI/mainwindow.h \
	../../../source/applications/gui/qt/GenesysQtGUI/qcustomplot.h \
	../../../source/examples/book/Book_Cap02_Example01.h \
	../../../source/examples/smarts/Smart_AssignWriteSeizes.h \
	../../../source/examples/smarts/Smart_BatchSeparate.h \
	../../../source/examples/smarts/Smart_CellularAutomata1.h \
	../../../source/examples/smarts/Smart_CppForG.h \
	../../../source/examples/smarts/Smart_Delay.h \
	../../../source/examples/smarts/Smart_Dummy.h \
	../../../source/examples/smarts/Smart_HoldSignal.h \
	../../../source/examples/smarts/Smart_ModelInfoModelSimulation.h \
	../../../source/examples/smarts/Smart_ODE.h \
	../../../source/examples/smarts/Smart_OnEvent.h \
	../../../source/examples/smarts/Smart_Parser.h \
	../../../source/examples/smarts/Smart_ParserModelFunctions.h \
	../../../source/examples/smarts/Smart_Plugin.h \
	../../../source/examples/smarts/Smart_Process.h \
	../../../source/examples/smarts/Smart_ProcessSet.h \
	../../../source/examples/smarts/Smart_RouteStation.h \
	../../../source/examples/smarts/Smart_SeizeDelayRelease.h \
	../../../source/examples/smarts/Smart_SeizeDelayReleaseMany.h \
	../../../source/examples/smarts/Smart_Sequence.h \
	../../../source/examples/teaching/AnElectronicAssemblyAndTestSystem.h \
	../../../source/examples/teaching/FullSimulationOfComplexModel.h \
	../../../source/examples/teaching/OperatingSystem02.h \
	../../../source/examples/teaching/OperatingSystem03.h \
	../../../source/kernel/TraitsKernel.h \
	../../../source/kernel/simulator/Attribute.h \
	../../../source/kernel/simulator/ComponentManager.h \
	../../../source/kernel/simulator/ConnectionManager.h \
	../../../source/kernel/simulator/Counter.h \
	../../../source/kernel/simulator/Entity.h \
	../../../source/kernel/simulator/EntityType.h \
	../../../source/kernel/simulator/Event.h \
	../../../source/kernel/simulator/ExperimentManager.h \
	../../../source/kernel/simulator/ExperimentManagerDefaultImpl1.h \
	../../../source/kernel/simulator/ExperimetManager_if.h \
	../../../source/kernel/simulator/LicenceManager.h \
	../../../source/kernel/simulator/Model.h \
	../../../source/kernel/simulator/ModelCheckerDefaultImpl1.h \
	../../../source/kernel/simulator/ModelChecker_if.h \
	../../../source/kernel/simulator/ModelComponent.h \
	../../../source/kernel/simulator/ModelDataDefinition.h \
	../../../source/kernel/simulator/ModelDataManager.h \
	../../../source/kernel/simulator/ModelInfo.h \
	../../../source/kernel/simulator/ModelManager.h \
	../../../source/kernel/simulator/ModelPersistenceDefaultImpl1.h \
	../../../source/kernel/simulator/ModelPersistence_if.h \
	../../../source/kernel/simulator/ModelSimulation.h \
	../../../source/kernel/simulator/OnEventManager.h \
	../../../source/kernel/simulator/ParserChangesInformation.h \
	../../../source/kernel/simulator/ParserDefaultImpl1.h \
	../../../source/kernel/simulator/ParserDefaultImpl2.h \
	../../../source/kernel/simulator/ParserManager.h \
	../../../source/kernel/simulator/Parser_if.h \
	../../../source/kernel/simulator/PersistentObject_base.h \
	../../../source/kernel/simulator/Plugin.h \
	../../../source/kernel/simulator/PluginConnectorDummyImpl1.h \
	../../../source/kernel/simulator/PluginConnector_if.h \
	../../../source/kernel/simulator/PluginInformation.h \
	../../../source/kernel/simulator/PluginManager.h \
	../../../source/kernel/simulator/Property.h \
	../../../source/kernel/simulator/PropertyManager.h \
	../../../source/kernel/simulator/ScenarioExperiment_if.h \
	../../../source/kernel/simulator/SimulationExperiment.h \
	../../../source/kernel/simulator/SimulationReporterDefaultImpl1.h \
	../../../source/kernel/simulator/SimulationReporter_if.h \
	../../../source/kernel/simulator/SimulationScenario.h \
	../../../source/kernel/simulator/Simulator.h \
	../../../source/kernel/simulator/SinkModelComponent.h \
	../../../source/kernel/simulator/SourceModelComponent.h \
	../../../source/kernel/simulator/StatisticsCollector.h \
	../../../source/kernel/simulator/TraceManager.h \
	../../../source/kernel/simulator/parserBisonFlex/Genesys++-driver.h \
	../../../source/kernel/simulator/parserBisonFlex/GenesysParser.h \
	../../../source/kernel/simulator/parserBisonFlex/location.hh \
	../../../source/kernel/simulator/parserBisonFlex/obj_t.h \
	../../../source/kernel/simulator/parserBisonFlex/parser/bisonparser.yy \
	../../../source/kernel/simulator/parserBisonFlex/parser/lexerparser.ll \
	../../../source/kernel/simulator/parserBisonFlex/position.hh \
	../../../source/kernel/simulator/parserBisonFlex/stack.hh \
	../../../source/kernel/statistics/CollectorDatafileDefaultImpl1.h \
	../../../source/kernel/statistics/CollectorDatafile_if.h \
	../../../source/kernel/statistics/CollectorDefaultImpl1.h \
	../../../source/kernel/statistics/Collector_if.h \
	../../../source/kernel/statistics/SamplerBoostImpl.h \
	../../../source/kernel/statistics/SamplerDefaultImpl1.h \
	../../../source/kernel/statistics/Sampler_if.h \
	../../../source/kernel/statistics/SorttFile.h \
	../../../source/kernel/statistics/StatisticsDataFileDefaultImpl.h \
	../../../source/kernel/statistics/StatisticsDataFile_if.h \
	../../../source/kernel/statistics/StatisticsDefaultImpl1.h \
	../../../source/kernel/statistics/Statistics_if.h \
	../../../source/kernel/util/Exact.h \
	../../../source/kernel/util/List.h \
	../../../source/kernel/util/ListObservable.h \
	../../../source/kernel/util/Util.h \
	../../../source/plugins/components/Access.h \
	../../../source/plugins/components/Assign.h \
	../../../source/plugins/components/Batch.h \
	../../../source/plugins/components/CellularAutomata.h \
	../../../source/plugins/components/CppForG.h \
	../../../source/plugins/components/Create.h \
	../../../source/plugins/components/Decide.h \
	../../../source/plugins/components/Delay.h \
	../../../source/plugins/components/Dispose.h \
	../../../source/plugins/components/DropOff.h \
	../../../source/plugins/components/DummyComponent.h \
	../../../source/plugins/components/Enter.h \
	../../../source/plugins/components/Exit.h \
	../../../source/plugins/components/Hold.h \
	../../../source/plugins/components/LSODE.h \
	../../../source/plugins/components/Leave.h \
	../../../source/plugins/components/MarkovChain.h \
	../../../source/plugins/components/Match.h \
	../../../source/plugins/components/OLD_ODEelement.h \
	../../../source/plugins/components/PickStation.h \
	../../../source/plugins/components/PickUp.h \
	../../../source/plugins/components/Process.h \
	../../../source/plugins/components/QueueableItem.h \
	../../../source/plugins/components/Record.h \
	../../../source/plugins/components/Release.h \
	../../../source/plugins/components/Remove.h \
	../../../source/plugins/components/Route.h \
	../../../source/plugins/components/Search.h \
	../../../source/plugins/components/SeizableItem.h \
	../../../source/plugins/components/Seize.h \
	../../../source/plugins/components/Separate.h \
	../../../source/plugins/components/Signal.h \
	../../../source/plugins/components/Start.h \
	../../../source/plugins/components/Stop.h \
	../../../source/plugins/components/Store.h \
	../../../source/plugins/components/Submodel.h \
	../../../source/plugins/components/Unstore.h \
	../../../source/plugins/components/Write.h \
	../../../source/plugins/data/AssignmentItem.h \
	../../../source/plugins/data/CppCode.h \
	../../../source/plugins/data/DummyElement.h \
	../../../source/plugins/data/EntityGroup.h \
	../../../source/plugins/data/Failure.h \
	../../../source/plugins/data/File.h \
	../../../source/plugins/data/Formula.h \
	../../../source/plugins/data/Label.h \
	../../../source/plugins/data/Queue.h \
	../../../source/plugins/data/Resource.h \
	../../../source/plugins/data/Schedule.h \
	../../../source/plugins/data/Sequence.h \
	../../../source/plugins/data/Set.h \
	../../../source/plugins/data/Station.h \
	../../../source/plugins/data/Storage.h \
	../../../source/plugins/data/Variable.h \
	../../../source/tools/HypothesisTesterDefaultImpl1.h \
	../../../source/tools/HypothesisTester_if.h \
	../../../source/tools/ProbabilityDistribution.h \
	../../../source/tools/SolverDefaultImpl1.h \
	../../../source/tools/TraitsTools.h \
	../../../source/tools/solver_if.h

FORMS += \
	../../../source/applications/gui/qt/GenesysQtGUI/dialogBreakpoint.ui \
	../../../source/applications/gui/qt/GenesysQtGUI/mainwindow.ui

TRANSLATIONS += \
	GenesysQtGUIQtCr_en_US.ts
CONFIG += lrelease
CONFIG += embed_translations

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
	../../../source/applications/gui/qt/GenesysQtGUI/simpleGUI_resources.qrc
